# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: server

steps:
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'Embold'
    method: 'POST'
    headers: |
      {
      "AuthToken": "Bearer $(Token)"
      }
    urlSuffix: '/repositories/128770b54001a3481c9747ed80b89afe/scan'
    waitForCompletion: 'false'
  